name: Deploy to JDCloud via Baota

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取最新代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 构建 Astro 项目
      - name: Install and Build (Astro)
        uses: withastro/action@v3

      # 3. 清空宝塔网站目录，避免旧文件残留
      - name: Clean old files on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /www/wwwroot/blog.pekko.top/*

      # 4. 上传 dist 文件夹内所有文件和隐藏文件到宝塔网站目录
      - name: Upload Files to Baota Website
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/www/wwwroot/blog.pekko.top"
          strip_components: 1
